<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>Исключения в Java и их обработка</title>
  <link href="%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B2%20Java%20%D0%B8%20%D0%B8%D1%85%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_files/style.css" rel="stylesheet" type="text/css">
  <link href="%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B2%20Java%20%D0%B8%20%D0%B8%D1%85%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_files/prettify.css" type="text/css" rel="stylesheet">
  <script type="text/javascript" src="%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B2%20Java%20%D0%B8%20%D0%B8%D1%85%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_files/prettify.js"></script>  
</head>

<body onload="prettyPrint()">
<div id="wrapper">
<div id="header">
<p><a href="http://kostin.ws/java/">← К списку</a></p>
<p>Теоретические материалы и задачи по Java</p>
</div>
<h1>Исключения и их обработка</h1>
<p>
	Исключениями или исключительными ситуациями (состояниями) называются ошибки, возникшие в программе во время её работы.</p>
<p>
	Все исключения в Java являются объектами. Поэтому они могут порождаться
 не только автоматически при возникновении исключительной ситуации, но и
 создаваться самим разработчиком.</p>
<p>
	Иерархия классов исключений:</p>
<p>
	<img src="%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B2%20Java%20%D0%B8%20%D0%B8%D1%85%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_files/exceptions-throwable.gif"></p>
<p>
	Исключения делятся на несколько классов, но все они имеют общего предка
 — класс Throwable. Его потомками являются подклассы Exception и Error.</p>
<p>
	Исключения (Exceptions) являются результатом проблем в программе, 
которые в принципе решаемы и предсказуемы. Например, произошло деление 
на ноль в целых числах.</p>
<p>
	Ошибки (Errors) представляют собой более серьёзные проблемы, которые, 
согласно спецификации Java, не следует пытаться обрабатывать в 
собственной программе, поскольку они связаны с проблемами уровня JVM. 
Например, исключения такого рода возникают, если закончилась память, 
доступная виртуальной машине. Программа дополнительную память всё равно 
не сможет обеспечить для JVM.</p>
<p>
	В Java все исключения делятся на три типа: контролируемые исключения 
(checked) и неконтролируемые исключения (unchecked), к которым относятся
 ошибки (Errors) и исключения времени выполнения (RuntimeExceptions, 
потомок класса Exception).</p>
<p>
	Контролируемые исключения представляют собой ошибки, которые можно и 
нужно обрабатывать в программе, к этому типу относятся все потомки 
класса Exception (но не RuntimeException).</p>
<p>
	Обработка исключения может быть произведена с помощью операторов 
try…catch, либо передана внешней части программы. Например, метод может 
передавать возникшие в нём исключения выше по иерархии вызовов, сам его 
не обрабатывая.</p>
<p>
	Неконтролируемые исключения не требуют обязательной обработки, однако, 
при желании, можно обрабатывать исключения класса RuntimeException.</p>
<p>
	Откомпилируем и запустим такую программу:</p>
<pre class="prettyprint java"><span class="kwd">class</span><span class="pln"> </span><span class="typ">Main</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp;</span><span class="kwd">public</span><span class="pln"> </span><span class="kwd">static</span><span class="pln"> </span><span class="kwd">void</span><span class="pln"> main</span><span class="pun">(</span><span class="typ">String</span><span class="pun">[]</span><span class="pln"> args</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="kwd">int</span><span class="pln"> a </span><span class="pun">=</span><span class="pln"> </span><span class="lit">4</span><span class="pun">;</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="pln">a</span><span class="pun">/</span><span class="lit">0</span><span class="pun">);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp;</span><span class="pun">}</span><span class="pln"> <br></span><span class="pun">}</span></pre>
<p>
	В момент запуска на консоль будет выведено следующее сообщение:</p>
<pre class="prettyprint java"><span class="typ">Exception</span><span class="pln"> </span><span class="kwd">in</span><span class="pln"> thread </span><span class="str">"main"</span><span class="pln"> java</span><span class="pun">.</span><span class="pln">lang</span><span class="pun">.</span><span class="typ">ArithmeticException</span><span class="pun">:</span><span class="pln"> </span><span class="pun">/</span><span class="pln"> </span><span class="kwd">by</span><span class="pln"> zero <br>&nbsp; &nbsp; &nbsp; &nbsp; at </span><span class="typ">Main</span><span class="pun">.</span><span class="pln">main</span><span class="pun">(</span><span class="typ">Main</span><span class="pun">.</span><span class="pln">java</span><span class="pun">:</span><span class="lit">4</span><span class="pun">)</span></pre>
<p>
	Из сообщения виден класс случившегося исключения — ArithmeticException. Это исключение можно обработать:</p>
<pre class="prettyprint java"><span class="kwd">class</span><span class="pln"> </span><span class="typ">Main</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp;</span><span class="kwd">public</span><span class="pln"> </span><span class="kwd">static</span><span class="pln"> </span><span class="kwd">void</span><span class="pln"> main</span><span class="pun">(</span><span class="typ">String</span><span class="pun">[]</span><span class="pln"> args</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="kwd">int</span><span class="pln"> a </span><span class="pun">=</span><span class="pln"> </span><span class="lit">4</span><span class="pun">;</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="kwd">try</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="pln">a</span><span class="pun">/</span><span class="lit">0</span><span class="pun">);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="pun">}</span><span class="pln"> </span><span class="kwd">catch</span><span class="pln"> </span><span class="pun">(</span><span class="typ">ArithmeticException</span><span class="pln"> e</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="str">"Произошла недопустимая арифметическая операция"</span><span class="pun">);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span><span class="pun">}</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp;</span><span class="pun">}</span><span class="pln"> <br></span><span class="pun">}</span></pre>
<p>
	Теперь вместо стандартного сообщения об ошибке будет выполняться блок catch, параметром которого является объект <strong>e</strong> соответствующего исключению класса (самому объекту можно давать любое имя, оно потребуется в том случае, если мы пожелаем снова принудительно выбросить это исключение, например, для того, чтобы оно было проверено каким-то ещё обработчиком).</p>
<p>
	В блок try при этом помещается тот фрагмент программы, где потенциально может возникнуть исключение.</p>
<p>
	Одному try может соответствовать сразу несколько блоков catch с разными классами исключений.</p>
<pre class="prettyprint java"><span class="kwd">import</span><span class="pln"> java</span><span class="pun">.</span><span class="pln">util</span><span class="pun">.</span><span class="typ">Scanner</span><span class="pun">;</span><span class="pln"> <br></span><span class="kwd">class</span><span class="pln"> </span><span class="typ">Main</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; </span><span class="kwd">public</span><span class="pln"> </span><span class="kwd">static</span><span class="pln"> </span><span class="kwd">void</span><span class="pln"> main</span><span class="pun">(</span><span class="typ">String</span><span class="pun">[]</span><span class="pln"> args</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp;</span><span class="kwd">int</span><span class="pun">[]</span><span class="pln"> m </span><span class="pun">=</span><span class="pln"> </span><span class="pun">{-</span><span class="lit">1</span><span class="pun">,</span><span class="lit">0</span><span class="pun">,</span><span class="lit">1</span><span class="pun">};</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">Scanner</span><span class="pln"> sc </span><span class="pun">=</span><span class="pln"> </span><span class="kwd">new</span><span class="pln"> </span><span class="typ">Scanner</span><span class="pun">(</span><span class="typ">System</span><span class="pun">.</span><span class="kwd">in</span><span class="pun">);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="kwd">try</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="kwd">int</span><span class="pln"> a </span><span class="pun">=</span><span class="pln"> sc</span><span class="pun">.</span><span class="pln">nextInt</span><span class="pun">();</span><span class="pln"> &nbsp; &nbsp; <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m</span><span class="pun">[</span><span class="pln">a</span><span class="pun">]</span><span class="pln"> </span><span class="pun">=</span><span class="pln"> </span><span class="lit">4</span><span class="pun">/</span><span class="pln">a</span><span class="pun">;</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="pln">m</span><span class="pun">[</span><span class="pln">a</span><span class="pun">]);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> </span><span class="kwd">catch</span><span class="pln"> </span><span class="pun">(</span><span class="typ">ArithmeticException</span><span class="pln"> e</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="str">"Произошла недопустимая арифметическая операция"</span><span class="pun">);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> </span><span class="kwd">catch</span><span class="pln"> </span><span class="pun">(</span><span class="typ">ArrayIndexOutOfBoundsException</span><span class="pln"> e</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="str">"Обращение по недопустимому индексу массива"</span><span class="pun">);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> <br>&nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> <br></span><span class="pun">}</span></pre>
<p>
	Если запустив представленную программу, пользователь введётся с клавиатуры 1 или 2, то программа отработает без создания каких-либо исключений.</p>
<p>
	Если пользователь введёт 0, то возникнет исключение класса ArithmeticException, и оно будет обработано первым блоком catch.</p>
<p>
	Если пользователь введёт 3, то возникнет исключение класса ArrayIndexOutOfBoundsException (выход за приделы массива), и оно будет обработано вторым блоком catch.</p>
<p>
	Если пользователь введёт нецелое число, например, 3.14, то возникнет исключение класса InputMismatchException (несоответствие типа вводимого значение), и оно будет выброшено в формате стандартной ошибки, поскольку его мы никак не обрабатывали.</p>
<p>
	Можно, однако, добавить обработчик для класса Exception, поскольку этот класс родительский для всех остальных контролируемых исключений, то он будет перехватывать любые из них (в том числе, и InputMismatchException).</p>
<pre class="prettyprint java"><span class="kwd">import</span><span class="pln"> java</span><span class="pun">.</span><span class="pln">util</span><span class="pun">.</span><span class="typ">Scanner</span><span class="pun">;</span><span class="pln"> <br></span><span class="kwd">class</span><span class="pln"> </span><span class="typ">Main</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; </span><span class="kwd">public</span><span class="pln"> </span><span class="kwd">static</span><span class="pln"> </span><span class="kwd">void</span><span class="pln"> main</span><span class="pun">(</span><span class="typ">String</span><span class="pun">[]</span><span class="pln"> args</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="kwd">int</span><span class="pun">[]</span><span class="pln"> m </span><span class="pun">=</span><span class="pln"> </span><span class="pun">{-</span><span class="lit">1</span><span class="pun">,</span><span class="lit">0</span><span class="pun">,</span><span class="lit">1</span><span class="pun">};</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="kwd">int</span><span class="pln"> a </span><span class="pun">=</span><span class="pln"> </span><span class="lit">1</span><span class="pun">;</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">Scanner</span><span class="pln"> sc </span><span class="pun">=</span><span class="pln"> </span><span class="kwd">new</span><span class="pln"> </span><span class="typ">Scanner</span><span class="pun">(</span><span class="typ">System</span><span class="pun">.</span><span class="kwd">in</span><span class="pun">);</span><span class="pln"> &nbsp; &nbsp; &nbsp; &nbsp;<br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="kwd">try</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a </span><span class="pun">=</span><span class="pln"> sc</span><span class="pun">.</span><span class="pln">nextInt</span><span class="pun">();</span><span class="pln"> &nbsp; &nbsp; <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m</span><span class="pun">[</span><span class="pln">a</span><span class="pun">-</span><span class="lit">1</span><span class="pun">]</span><span class="pln"> </span><span class="pun">=</span><span class="pln"> </span><span class="lit">4</span><span class="pun">/</span><span class="pln">a</span><span class="pun">;</span><span class="pln"><br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="pln">m</span><span class="pun">[</span><span class="pln">a</span><span class="pun">]);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> </span><span class="kwd">catch</span><span class="pln"> </span><span class="pun">(</span><span class="typ">ArithmeticException</span><span class="pln"> e</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="str">"Произошла недопустимая арифметическая операция"</span><span class="pun">);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> </span><span class="kwd">catch</span><span class="pln"> </span><span class="pun">(</span><span class="typ">ArrayIndexOutOfBoundsException</span><span class="pln"> e</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="str">"Обращение по недопустимому индексу массива"</span><span class="pun">);</span><span class="pln"> &nbsp; &nbsp; &nbsp; <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> </span><span class="kwd">catch</span><span class="pln"> </span><span class="pun">(</span><span class="typ">Exception</span><span class="pln"> e</span><span class="pun">)</span><span class="pln"> </span><span class="pun">{</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span class="typ">System</span><span class="pun">.</span><span class="kwd">out</span><span class="pun">.</span><span class="pln">println</span><span class="pun">(</span><span class="str">"Произошло ещё какое-то исключение"</span><span class="pun">);</span><span class="pln"> <br>&nbsp; &nbsp; &nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> <br>&nbsp; &nbsp; </span><span class="pun">}</span><span class="pln"> <br></span><span class="pun">}</span></pre>
<p>
	Поскольку исключения построены на иерархии классов и подклассов, то сначала надо пытаться обработать более частные исключения и лишь затем более общие. То есть поставив первым (а не третьим) блок с обработкой исключения класса Exception, мы бы никогда не увидели никаких сообщений об ошибке, кроме «Произошло ещё какое-то исключение» (все исключения перехватились бы сразу этим блоком и не доходили бы до остальных).</p>
<p>
	Необязательным добавлением к блокам try…catch может быть блок finally. Помещенные в него команды будут выполняться в любом случае, вне зависимости от того, произошло ли исключение или нет. При том, что при возникновении необработанного исключения оставшаяся после генерации этого исключения часть программы — не выполняется. Например, если исключение возникло в процессе каких-то длительных вычислений, в блоке finally можно показать или сохранить промежуточные результаты.</p>


<div id="footer">
<p>©&nbsp;2010, Алексей Николаевич Костин. Кафедра ТИДМ математического факультета МПГУ.</p>
</div>
</div>

<!-- Yandex.Metrika -->
<script src="%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B2%20Java%20%D0%B8%20%D0%B8%D1%85%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_files/watch.js" type="text/javascript"></script>
<div style="display:none;"><script type="text/javascript">
try { var yaCounter1088324 = new Ya.Metrika(1088324); } catch(e){}
</script></div>
<noscript><div style="position:absolute"><img src="//mc.yandex.ru/watch/1088324" alt="" /></div></noscript>
<!-- /Yandex.Metrika -->


</body></html>